### ISSUE TITLE
login screen fix

### ISSUE THREAD

**Issue by ahmetyaka** [CankayaUniversity/ceng-407-408-2023-2024-Daily-An-AI-Powered-Diary-with-Image-Generation#4]
we need to fix network error on mobile devices

**Comment by fatihkapiz** [comment]
check out these:

-  https://github.com/expo/expo/issues/16451
- https://stackoverflow.com/questions/65697750/react-native-expo-network-error-on-android

**Comment by fatihkapiz** [comment]
Issue is related to server running on localhost:9090. mobile expo go can not reach this path. Use:

`npx expo prebuild`
`npx expo run:ios|android` 

instead to start an emulator on the development environment. Temporary fix until server is deployed on a remote server. Then the problem will be fixed anyways.
